apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-html-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dummy-html
  template:
    metadata:
      labels:
        app: dummy-html
    spec:
      containers:
      - name: web
        image: prasadrpatil/dummy-html-app:latest
        ports:
        - containerPort: 8080  # Make sure this matches the port your app is listening on inside the container

---

apiVersion: v1
kind: Service
metadata:
  name: dummy-html-service
spec:
  selector:
    app: dummy-html
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080  # Update the target port to match the container port
  type: NodePort
